# t"ü 1.0 from acme/x, as released at 1.0.
# Generated by truvity/ci-workflows release-public; do not edit.
#
# devbox.json:
#   "https://github.com/acme/x/releases/download/1.0/t"ü_1.0_nix-flake.tar.gz#t"ü": ""
{
  description = "t\"\u00fc 1.0 (acme/x 1.0)";

  inputs.nixpkgs.url = "github:NixOS/nixpkgs/nixpkgs-unstable";

  outputs = { self, nixpkgs }:
    let
      version = "1.0";
      sources = {
        "aarch64-linux" = { url = "https://github.com/acme/x/releases/download/1.0/t_arm64.tar.xz"; sha256 = "6af1e0f9ebd1e771786eae27eadf45a1f66c494a68020ff780387fe0683b6e07"; };
        "x86_64-linux" = { url = "https://github.com/acme/x/releases/download/1.0/t_amd64.tar.xz"; sha256 = "b02307514562c4fcdd314a56c8841434388ef4103da5211015f85ac756f31ba8"; };
      };
      package = system:
        let pkgs = nixpkgs.legacyPackages.${system};
        in pkgs.stdenvNoCC.mkDerivation {
          pname = "t\"\u00fc";
          inherit version;
          src = pkgs.fetchurl sources.${system};
          sourceRoot = ".";
          dontConfigure = true;
          dontBuild = true;
          installPhase = ''
            runHook preInstall
            install -Dm755 "t"ü" "$out/bin/t"ü"
            install -Dm755 "x" "$out/bin/x"
            runHook postInstall
          '';
          meta.mainProgram = "t\"\u00fc";
        };
    in {
      packages = nixpkgs.lib.genAttrs (builtins.attrNames sources) (system: {
        "t\"\u00fc" = package system;
        default = package system;
      });
    };
}
