// Package releasepublic holds the shell steps of the public release workflow
// that carry rules: which charts a release publishes and under which names,
// and the Nix flakes generated from GoReleaser's archives. gh, helmctl, nix,
// tar and gzip stay the executed programs.
package releasepublic

import (
	"bytes"
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"unicode/utf16"

	"github.com/truvity/ci-actions/internal/runcmd"
)

// ErrFailed marks a failure whose message is already written.
var ErrFailed = errors.New("release-public: failed")

// NixOptions are the Publish Nix flakes step's environment.
type NixOptions struct {
	Repo     string // GITHUB_REPOSITORY
	Tag      string // GITHUB_REF_NAME
	Flakes   string // FLAKES: JSON array of archive ids
	FlakeDir string // FLAKE_DIR
	Dir      string // the checkout, where devbox.lock and dist/ are; "" is the working directory
	Out      io.Writer
	Err      io.Writer
	Exec     runcmd.Exec
}

// goreleaser os/arch to Nix system. Anything else has no Nix system and is
// left out: windows, 386, arm/v6, and darwin/amd64, which nixpkgs-unstable
// dropped in 26.11, so a flake offering it fails to evaluate there.
var systems = map[[2]string]string{
	{"linux", "amd64"}:  "x86_64-linux",
	{"linux", "arm64"}:  "aarch64-linux",
	{"darwin", "arm64"}: "aarch64-darwin",
}

var (
	nixpkgsPin     = regexp.MustCompile(`^github:NixOS/nixpkgs/[0-9a-f]{40}$`)
	archiveFormats = map[string]bool{"tar.gz": true, "tgz": true, "tar.xz": true, "tar.zst": true, "zip": true}
)

type artifact struct {
	Type   string `json:"type"`
	Name   string `json:"name"`
	Path   string `json:"path"`
	Goos   string `json:"goos"`
	Goarch string `json:"goarch"`
	Amd64  string `json:"goamd64"`
	Extra  struct {
		ID        string   `json:"ID"`
		Format    string   `json:"Format"`
		Binaries  []string `json:"Binaries"`
		WrappedIn string   `json:"WrappedIn"`
	} `json:"extra"`
}

// nixString is json.dumps: a JSON string literal is a valid Nix string, and
// ASCII only, as the generator that wrote the published flakes did.
func nixString(s string) string {
	var b strings.Builder
	b.WriteByte('"')
	for _, r := range s {
		switch {
		case r == '"':
			b.WriteString(`\"`)
		case r == '\\':
			b.WriteString(`\\`)
		case r == '\n':
			b.WriteString(`\n`)
		case r == '\r':
			b.WriteString(`\r`)
		case r == '\t':
			b.WriteString(`\t`)
		case r == '\b':
			b.WriteString(`\b`)
		case r == '\f':
			b.WriteString(`\f`)
		case r < 0x20:
			fmt.Fprintf(&b, `\u%04x`, r)
		case r < 0x7f || r == 0x7f:
			b.WriteRune(r)
		case r > 0xffff:
			r1, r2 := utf16.EncodeRune(r)
			fmt.Fprintf(&b, `\u%04x\u%04x`, r1, r2)
		default:
			fmt.Fprintf(&b, `\u%04x`, r)
		}
	}
	b.WriteByte('"')
	return b.String()
}

// callerNixpkgs is the nixpkgs the flake builds with: the caller's own devbox
// pin when it has one, so the release runner and most consumers already hold
// it. The first pin in file order wins.
func callerNixpkgs(lock []byte) string {
	const unstable = "github:NixOS/nixpkgs/nixpkgs-unstable"
	dec := json.NewDecoder(bytes.NewReader(lock))
	if tok, err := dec.Token(); err != nil || tok != json.Delim('{') {
		return unstable
	}
	for dec.More() {
		k, err := dec.Token()
		if err != nil {
			return unstable
		}
		if k != "packages" {
			var skip json.RawMessage
			if dec.Decode(&skip) != nil {
				return unstable
			}
			continue
		}
		if tok, err := dec.Token(); err != nil || tok != json.Delim('{') {
			return unstable
		}
		for dec.More() {
			name, err := dec.Token()
			if err != nil {
				return unstable
			}
			var entry struct {
				Resolved string `json:"resolved"`
			}
			if dec.Decode(&entry) != nil {
				continue
			}
			if strings.HasPrefix(name.(string), "github:NixOS/nixpkgs/") {
				resolved, _, _ := strings.Cut(entry.Resolved, "?")
				if nixpkgsPin.MatchString(resolved) {
					return resolved
				}
			}
		}
		return unstable
	}
	return unstable
}

type source struct{ url, sha256 string }

// flakeFor writes the text of one archive's flake.nix.
func flakeFor(repo, tag, version, nixpkgs, id string, sources map[string]source, binaries []string, wrapped string) string {
	main := binaries[0]
	for _, b := range binaries {
		if b == id {
			main = id
		}
	}
	l := []string{
		fmt.Sprintf("# %s %s from %s, as released at %s.", id, version, repo, tag),
		"# Generated by truvity/ci-workflows release-public; do not edit.",
		"#",
		"# devbox.json:",
		fmt.Sprintf(`#   "https://github.com/%s/releases/download/%s/%s_%s_nix-flake.tar.gz#%s": ""`, repo, tag, id, version, id),
		"{",
		fmt.Sprintf("  description = %s;", nixString(fmt.Sprintf("%s %s (%s %s)", id, version, repo, tag))),
		"",
		fmt.Sprintf("  inputs.nixpkgs.url = %s;", nixString(nixpkgs)),
		"",
		"  outputs = { self, nixpkgs }:",
		"    let",
		fmt.Sprintf("      version = %s;", nixString(version)),
		"      sources = {",
	}
	var keys []string
	for k := range sources {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, k := range keys {
		s := sources[k]
		l = append(l, fmt.Sprintf("        %s = { url = %s; sha256 = %s; };", nixString(k), nixString(s.url), nixString(s.sha256)))
	}
	if wrapped == "" {
		wrapped = "."
	}
	l = append(l,
		"      };",
		"      package = system:",
		"        let pkgs = nixpkgs.legacyPackages.${system};",
		"        in pkgs.stdenvNoCC.mkDerivation {",
		fmt.Sprintf("          pname = %s;", nixString(id)),
		"          inherit version;",
		"          src = pkgs.fetchurl sources.${system};",
		fmt.Sprintf("          sourceRoot = %s;", nixString(wrapped)),
		"          dontConfigure = true;",
		"          dontBuild = true;",
		"          installPhase = ''",
		"            runHook preInstall",
	)
	for _, b := range binaries {
		l = append(l, fmt.Sprintf(`            install -Dm755 "%s" "$out/bin/%s"`, b, b))
	}
	l = append(l,
		"            runHook postInstall",
		"          '';",
		fmt.Sprintf("          meta.mainProgram = %s;", nixString(main)),
		"        };",
		"    in {",
		"      packages = nixpkgs.lib.genAttrs (builtins.attrNames sources) (system: {",
		fmt.Sprintf("        %s = package system;", nixString(id)),
		"        default = package system;",
		"      });",
		"    };",
		"}",
	)
	return strings.Join(l, "\n") + "\n"
}

// GenerateFlakes writes one flake directory per archive id under o.FlakeDir
// and returns them. It reads devbox.lock (optional) and dist/artifacts.json.
func GenerateFlakes(o NixOptions) ([]string, error) {
	fail := func(format string, a ...any) ([]string, error) {
		fmt.Fprintf(o.Err, "::error::"+format+"\n", a...)
		return nil, ErrFailed
	}
	version := strings.TrimPrefix(o.Tag, "v")
	var ids []string
	if err := json.Unmarshal([]byte(o.Flakes), &ids); err != nil {
		return nil, fmt.Errorf("nix-flakes is not a JSON array of archive ids: %w", err)
	}
	nixpkgs := "github:NixOS/nixpkgs/nixpkgs-unstable"
	if b, err := os.ReadFile(filepath.Join(o.Dir, "devbox.lock")); err == nil {
		nixpkgs = callerNixpkgs(b)
	} else if !os.IsNotExist(err) {
		return nil, err
	}
	raw, err := os.ReadFile(filepath.Join(o.Dir, "dist", "artifacts.json"))
	if err != nil {
		return nil, err
	}
	var artifacts []artifact
	if err := json.Unmarshal(raw, &artifacts); err != nil {
		return nil, fmt.Errorf("dist/artifacts.json: %w", err)
	}

	var dirs []string
	for _, id := range ids {
		sources := map[string]source{}
		var binaries []string
		wrapped, haveBinaries := "", false
		for _, art := range artifacts {
			if art.Type != "Archive" || art.Extra.ID != id {
				continue
			}
			system, ok := systems[[2]string{art.Goos, art.Goarch}]
			amd64 := art.Amd64
			if amd64 == "" {
				amd64 = "v1"
			}
			if !ok || amd64 != "v1" {
				continue
			}
			if !archiveFormats[art.Extra.Format] {
				return fail("archive %s is %s; a flake needs an archive, not a bare binary", art.Name, art.Extra.Format)
			}
			if !haveBinaries {
				binaries, wrapped, haveBinaries = art.Extra.Binaries, art.Extra.WrappedIn, true
			} else if strings.Join(art.Extra.Binaries, "\x00") != strings.Join(binaries, "\x00") || art.Extra.WrappedIn != wrapped {
				return fail("archive %s holds different binaries per platform", id)
			}
			b, err := os.ReadFile(filepath.Join(o.Dir, art.Path))
			if err != nil {
				return nil, err
			}
			sum := sha256.Sum256(b)
			sources[system] = source{
				url:    fmt.Sprintf("https://github.com/%s/releases/download/%s/%s", o.Repo, o.Tag, art.Name),
				sha256: hex.EncodeToString(sum[:]),
			}
		}
		if len(sources) == 0 {
			return fail("no linux or darwin archive with id %s in dist/artifacts.json", id)
		}
		if len(binaries) == 0 {
			return fail("archive %s lists no binaries", id)
		}
		name := fmt.Sprintf("%s_%s_nix-flake", id, version)
		dir := filepath.Join(o.FlakeDir, name)
		if err := os.MkdirAll(dir, 0o755); err != nil {
			return nil, err
		}
		if err := os.WriteFile(filepath.Join(dir, "flake.nix"), []byte(flakeFor(o.Repo, o.Tag, version, nixpkgs, id, sources, binaries, wrapped)), 0o644); err != nil {
			return nil, err
		}
		var ks []string
		for k := range sources {
			ks = append(ks, k)
		}
		sort.Strings(ks)
		fmt.Fprintf(o.Out, "%s: %s with %s\n", dir, strings.Join(ks, ", "), nixpkgs)
		dirs = append(dirs, name)
	}
	return dirs, nil
}

// PublishFlakes generates the flakes, locks, checks and builds each, packs it
// deterministically (so re-running a release uploads the same bytes) and
// uploads it to the release.
func PublishFlakes(ctx context.Context, o NixOptions) error {
	if o.Exec == nil {
		o.Exec = runcmd.OS
	}
	if o.Out == nil {
		o.Out = io.Discard
	}
	if o.Err == nil {
		o.Err = io.Discard
	}
	if _, err := GenerateFlakes(o); err != nil {
		return err
	}
	// The loop runs over what is in the flake directory, in glob order.
	entries, err := os.ReadDir(o.FlakeDir)
	if err != nil {
		return err
	}
	nix := func(args ...string) []string {
		return append([]string{"--extra-experimental-features", "nix-command flakes"}, args...)
	}
	run := func(c runcmd.Cmd) error {
		c.Dir = o.FlakeDir
		if c.Stdout == nil {
			c.Stdout = o.Out
		}
		c.Stderr = o.Err
		return o.Exec(ctx, c)
	}
	for _, e := range entries { // os.ReadDir is sorted by name
		if !e.IsDir() {
			continue
		}
		dir := e.Name()
		id := strings.TrimSuffix(dir, "_"+strings.TrimPrefix(o.Tag, "v")+"_nix-flake")
		path := "path:" + o.FlakeDir + "/" + dir
		fmt.Fprintf(o.Out, "::group::%s\n", dir)
		if err := run(runcmd.Cmd{Name: "nix", Args: nix("flake", "lock", path)}); err != nil {
			return fmt.Errorf("nix flake lock: %w", err)
		}
		if err := run(runcmd.Cmd{Name: "nix", Args: nix("flake", "check", "--no-build", "--all-systems", path)}); err != nil {
			return fmt.Errorf("nix flake check: %w", err)
		}
		var built bytes.Buffer
		if err := run(runcmd.Cmd{Name: "nix", Args: nix("build", "--no-link", "--print-out-paths", path+"#"+id), Stdout: &built}); err != nil {
			return fmt.Errorf("nix build: %w", err)
		}
		out := strings.TrimRight(built.String(), "\n")
		if err := run(runcmd.Cmd{Name: "ls", Args: []string{"-l", out + "/bin"}}); err != nil {
			return fmt.Errorf("ls: %w", err)
		}
		if err := packDeterministic(ctx, o, dir); err != nil {
			return err
		}
		if err := run(runcmd.Cmd{Name: "gh", Args: []string{"release", "upload", o.Tag, dir + ".tar.gz", "--clobber", "--repo", o.Repo}}); err != nil {
			return fmt.Errorf("gh release upload: %w", err)
		}
		fmt.Fprintln(o.Out, "::endgroup::")
	}
	return nil
}

// packDeterministic is
//
//	tar --sort=name --owner=0 --group=0 --numeric-owner --mtime=@0 -cf - DIR | gzip -n > DIR.tar.gz
//
// so a consumer's locked narHash still matches a re-uploaded asset.
func packDeterministic(ctx context.Context, o NixOptions, dir string) error {
	f, err := os.Create(filepath.Join(o.FlakeDir, dir+".tar.gz"))
	if err != nil {
		return err
	}
	defer f.Close()
	pr, pw := io.Pipe()
	tarErr := make(chan error, 1)
	go func() {
		err := o.Exec(ctx, runcmd.Cmd{Dir: o.FlakeDir, Name: "tar", Args: []string{"--sort=name", "--owner=0", "--group=0", "--numeric-owner", "--mtime=@0", "-cf", "-", dir}, Stdout: pw, Stderr: o.Err})
		pw.CloseWithError(err)
		tarErr <- err
	}()
	gzErr := o.Exec(ctx, runcmd.Cmd{Dir: o.FlakeDir, Name: "gzip", Args: []string{"-n"}, Stdin: pr, Stdout: f, Stderr: o.Err})
	pr.Close()
	if err := <-tarErr; err != nil {
		return fmt.Errorf("tar: %w", err)
	}
	if gzErr != nil {
		return fmt.Errorf("gzip: %w", gzErr)
	}
	return nil
}
