# other 1.2.3 from acme/tool, as released at v1.2.3.
# Generated by truvity/ci-workflows release-public; do not edit.
#
# devbox.json:
#   "https://github.com/acme/tool/releases/download/v1.2.3/other_1.2.3_nix-flake.tar.gz#other": ""
{
  description = "other 1.2.3 (acme/tool v1.2.3)";

  inputs.nixpkgs.url = "github:NixOS/nixpkgs/0123456789abcdef0123456789abcdef01234567";

  outputs = { self, nixpkgs }:
    let
      version = "1.2.3";
      sources = {
        "x86_64-linux" = { url = "https://github.com/acme/tool/releases/download/v1.2.3/other_1.2.3_linux_amd64.zip"; sha256 = "1940fe02735e626b70b42bfdadc1b34dcd1d2d8f4f9cf903b6e4508e3866cb49"; };
      };
      package = system:
        let pkgs = nixpkgs.legacyPackages.${system};
        in pkgs.stdenvNoCC.mkDerivation {
          pname = "other";
          inherit version;
          src = pkgs.fetchurl sources.${system};
          sourceRoot = ".";
          dontConfigure = true;
          dontBuild = true;
          installPhase = ''
            runHook preInstall
            install -Dm755 "a" "$out/bin/a"
            install -Dm755 "b" "$out/bin/b"
            runHook postInstall
          '';
          meta.mainProgram = "a";
        };
    in {
      packages = nixpkgs.lib.genAttrs (builtins.attrNames sources) (system: {
        "other" = package system;
        default = package system;
      });
    };
}
