# tool 1.2.3 from acme/tool, as released at v1.2.3.
# Generated by truvity/ci-workflows release-public; do not edit.
#
# devbox.json:
#   "https://github.com/acme/tool/releases/download/v1.2.3/tool_1.2.3_nix-flake.tar.gz#tool": ""
{
  description = "tool 1.2.3 (acme/tool v1.2.3)";

  inputs.nixpkgs.url = "github:NixOS/nixpkgs/0123456789abcdef0123456789abcdef01234567";

  outputs = { self, nixpkgs }:
    let
      version = "1.2.3";
      sources = {
        "aarch64-darwin" = { url = "https://github.com/acme/tool/releases/download/v1.2.3/tool_1.2.3_darwin_arm64.tar.gz"; sha256 = "9d9cbcf37acd9d54a8d5300db46410d5301d2472f11c43691bf96bf825fa25da"; };
        "aarch64-linux" = { url = "https://github.com/acme/tool/releases/download/v1.2.3/tool_1.2.3_linux_arm64.tar.gz"; sha256 = "1edf379380f595134a86c5c2c58f1de55424ac7f24ee65bb9fe87444eca6d3cc"; };
        "x86_64-linux" = { url = "https://github.com/acme/tool/releases/download/v1.2.3/tool_1.2.3_linux_amd64.tar.gz"; sha256 = "8956314d1a0f6415445f6e7a0fb4cc78a21e3521d8fbb2a9c890271580cfab5c"; };
      };
      package = system:
        let pkgs = nixpkgs.legacyPackages.${system};
        in pkgs.stdenvNoCC.mkDerivation {
          pname = "tool";
          inherit version;
          src = pkgs.fetchurl sources.${system};
          sourceRoot = "tool_1.2.3";
          dontConfigure = true;
          dontBuild = true;
          installPhase = ''
            runHook preInstall
            install -Dm755 "tool" "$out/bin/tool"
            install -Dm755 "tool-helper" "$out/bin/tool-helper"
            runHook postInstall
          '';
          meta.mainProgram = "tool";
        };
    in {
      packages = nixpkgs.lib.genAttrs (builtins.attrNames sources) (system: {
        "tool" = package system;
        default = package system;
      });
    };
}
