package devboxparity

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

var playwrightPkgRe = regexp.MustCompile(`^playwright(-driver|-test)?@`)

type member struct {
	key string
	val json.RawMessage
}

// members reads a JSON object IN ORDER, which a Go map cannot: the first
// playwright package of devbox.lock is the one that counts.
func members(raw []byte) ([]member, error) {
	dec := json.NewDecoder(bytes.NewReader(raw))
	tok, err := dec.Token()
	if err != nil {
		return nil, err
	}
	if d, ok := tok.(json.Delim); !ok || d != '{' {
		return nil, nil // null, an array or a scalar: no members
	}
	var out []member
	for dec.More() {
		k, err := dec.Token()
		if err != nil {
			return nil, err
		}
		var v json.RawMessage
		if err := dec.Decode(&v); err != nil {
			return nil, err
		}
		out = append(out, member{k.(string), v})
	}
	return out, nil
}

func truthyString(raw json.RawMessage) (string, bool) {
	var s string
	if json.Unmarshal(raw, &s) == nil && s != "" {
		return s, true
	}
	return "", false
}

// Pair: playwright. The nix package ships the browsers; the npm package
// must match it exactly or the tests run a driver the browsers were not
// built for. The devbox.lock version is the truth; package.json follows,
// and the lockfile is regenerated by the repository's own package manager
// so nothing else in it moves.
func (r *run) alignPlaywright(ctx context.Context) error {
	lockPath := filepath.Join(r.o.WorkDir, "devbox.lock")
	pkgPath := filepath.Join(r.o.WorkDir, "package.json")
	lock, lerr := os.ReadFile(lockPath)
	pkg, perr := os.ReadFile(pkgPath)
	if lerr != nil || perr != nil {
		r.printf("no devbox.lock + package.json pair — nothing to align\n")
		return nil
	}

	var lockDoc struct {
		Packages json.RawMessage `json:"packages"`
	}
	if err := json.Unmarshal(lock, &lockDoc); err != nil {
		return fmt.Errorf("devbox.lock: %w", err)
	}
	pkgs, err := members(lockDoc.Packages)
	if err != nil {
		return fmt.Errorf("devbox.lock: %w", err)
	}
	want := ""
	for _, p := range pkgs {
		if !playwrightPkgRe.MatchString(p.key) {
			continue
		}
		var v struct {
			Version json.RawMessage `json:"version"`
		}
		if json.Unmarshal(p.val, &v) != nil {
			continue
		}
		if s, ok := truthyString(v.Version); ok {
			want = s
			break
		}
	}
	if want == "" {
		r.printf("devbox does not pin playwright — nothing to align\n")
		return nil
	}

	top, err := members(pkg)
	if err != nil {
		return fmt.Errorf("package.json: %w", err)
	}
	have := ""
	var spans []span
	var pm string
	for _, m := range top {
		switch m.key {
		case "packageManager":
			pm, _ = truthyString(m.val)
		}
	}
	for _, section := range []string{"dependencies", "devDependencies"} {
		for _, m := range top {
			if m.key != section {
				continue
			}
			deps, err := members(m.val)
			if err != nil {
				return fmt.Errorf("package.json: %w", err)
			}
			byKey := map[string]json.RawMessage{}
			for _, d := range deps {
				byKey[d.key] = d.val
			}
			if have == "" {
				if s, ok := truthyString(byKey["@playwright/test"]); ok {
					have = s
				} else if s, ok := truthyString(byKey["playwright"]); ok {
					have = s
				}
			}
		}
	}
	if have == "" {
		r.printf("package.json does not depend on playwright — nothing to align\n")
		return nil
	}
	if have == want {
		r.printf("playwright %s already aligned\n", want)
		return nil
	}
	r.printf("aligning playwright %s -> %s (devbox leads)\n", have, want)

	// Rewrite only the values of the two keys, in place, so nothing else in
	// the file moves (key order, indentation, escapes and numbers all stay
	// as the repository wrote them).
	spans, err = playwrightSpans(pkg)
	if err != nil {
		return fmt.Errorf("package.json: %w", err)
	}
	quoted, _ := jsonString(want)
	sort.Slice(spans, func(i, j int) bool { return spans[i].start > spans[j].start })
	out := append([]byte(nil), pkg...)
	for _, s := range spans {
		out = append(out[:s.start], append([]byte(quoted), out[s.end:]...)...)
	}
	if err := os.WriteFile(pkgPath, out, 0o644); err != nil {
		return err
	}

	// Regenerate the lockfile with the repository's own package manager,
	// through devbox so the pinned manager is the one that runs.
	has := func(name string) bool {
		_, err := os.Stat(filepath.Join(r.o.WorkDir, name))
		return err == nil
	}
	var args []string
	switch {
	case has("yarn.lock"):
		if pm == "" || strings.HasPrefix(pm, "yarn@1") {
			args = []string{"yarn", "install", "--ignore-scripts"}
		} else {
			args = []string{"yarn", "install", "--mode=update-lockfile"}
		}
	case has("pnpm-lock.yaml"):
		args = []string{"pnpm", "install", "--lockfile-only"}
	case has("package-lock.json"):
		args = []string{"npm", "install", "--package-lock-only", "--ignore-scripts"}
	default:
		r.printf("::warning::no lockfile found — package.json moved, nothing else\n")
	}
	if args != nil {
		if err := r.devbox(ctx, ".", r.stdout(), r.stderr(), args...); err != nil {
			return fmt.Errorf("%s: %w", strings.Join(args, " "), err)
		}
	}
	if err := r.cmd(ctx, ".", r.stdout(), r.stderr(), "git", "diff", "--stat"); err != nil {
		return fmt.Errorf("git diff --stat: %w", err)
	}
	return nil
}

type span struct{ start, end int }

// playwrightSpans finds the byte spans of the values of "@playwright/test"
// and "playwright" inside the top-level dependencies and devDependencies.
func playwrightSpans(data []byte) ([]span, error) {
	dec := json.NewDecoder(bytes.NewReader(data))
	if tok, err := dec.Token(); err != nil {
		return nil, err
	} else if d, ok := tok.(json.Delim); !ok || d != '{' {
		return nil, errors.New("not an object")
	}
	var spans []span
	for dec.More() {
		kt, err := dec.Token()
		if err != nil {
			return nil, err
		}
		key := kt.(string)
		if key != "dependencies" && key != "devDependencies" {
			var skip json.RawMessage
			if err := dec.Decode(&skip); err != nil {
				return nil, err
			}
			continue
		}
		var raw json.RawMessage
		if err := dec.Decode(&raw); err != nil {
			return nil, err
		}
		end := int(dec.InputOffset())
		base := end - len(raw)
		inner := json.NewDecoder(bytes.NewReader(raw))
		if tok, err := inner.Token(); err != nil {
			return nil, err
		} else if d, ok := tok.(json.Delim); !ok || d != '{' {
			continue
		}
		for inner.More() {
			kt, err := inner.Token()
			if err != nil {
				return nil, err
			}
			var v json.RawMessage
			if err := inner.Decode(&v); err != nil {
				return nil, err
			}
			if k := kt.(string); k == "@playwright/test" || k == "playwright" {
				e := int(inner.InputOffset())
				spans = append(spans, span{base + e - len(v), base + e})
			}
		}
	}
	return spans, nil
}

func jsonString(s string) (string, error) {
	var b bytes.Buffer
	enc := json.NewEncoder(&b)
	enc.SetEscapeHTML(false)
	if err := enc.Encode(s); err != nil {
		return "", err
	}
	return strings.TrimRight(b.String(), "\n"), nil
}

func unmarshalStrings(s string, out *[]string) error { return json.Unmarshal([]byte(s), out) }
